### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by Sirse** [aatrubilin/hassio-torrserver#1]
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
/run.sh: line 5: ARCH_MAP[${BUILD_ARCH}]: unbound variable
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by taranton** [comment]
Same problem

**Comment by zamarawka** [comment]
@Sirse @taranton Fixed this issue in #2.
As temporal solution, until it get merged, you could use my repo `https://github.com/zamarawka/hassio-torrserver` as "Repositories" in "Add-on Store"

**Comment by Sirse** [comment]
Fixed, ty!

**Comment by lordzid** [comment]
такая же проблема

HAos rpi4

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
/run.sh: line 5: ARCH_MAP[${BUILD_ARCH}]: unbound variable
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by aatrubilin** [comment]
@lordzid привет. Это полный лог запуска? 

По идее должен в логах писать текущую архитектуру, но в твоем логе не вижу( 

https://github.com/aatrubilin/hassio-torrserver/blob/master/torrserver/rootfs/run.sh#L6
