### ISSUE TITLE
Логин и пароль

### ISSUE THREAD

**Issue by ju0k** [aatrubilin/hassio-torrserver#17]
Есть ли возможность добавить функционал в виде логина и пароля? 
Если вешать дома на сервер с доступом извне чтобы не сажать батарейку на телефонах/планшетах то без защиты сможет кто угодно подключиться и загрузить сервер.

**Comment by aatrubilin** [comment]
Да, конечно. TorrServer поддерживает http auth, вынесу в параметры. 

Постараюсь подготовить до конца недели.

**Comment by aatrubilin** [comment]
@ju0k привет!

Добавил авторизацию в версии 1.0.0-MatriX.132

Затести плс, и кинь, пожалуйста лог запуска - вот эту часть (хочу собрать статистику на каких архитекутах успешно работает аддон)

![image](https://github.com/aatrubilin/hassio-torrserver/assets/29011393/98a50c7b-8eb7-49d5-a543-9e987ec2477d)

**Comment by aatrubilin** [comment]
в конфиге нужно включить авторизацию и задать пользователей

![image](https://github.com/aatrubilin/hassio-torrserver/assets/29011393/142eefbe-4422-4ceb-b53e-4c69ddb06178)

**Comment by ju0k** [comment]
Пока не прилетело обновление, версия 0.2.17

**Comment by aatrubilin** [comment]
Ты можешь вручную обновить репозитории в магазине дополнений.

**Comment by aatrubilin** [comment]
![Screenshot_20240424-005347.png](https://github.com/aatrubilin/hassio-torrserver/assets/29011393/49e4e2cf-1ebb-426c-87db-91ac1ebd14d7)

**Comment by ju0k** [comment]
Тупанул, спасибо!
![Uploading Screenshot_20240423_205843_Home Assistant.jpg…]()
