### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by gizeasy** [aatrubilin/hassio-torrserver#3]
```
The command '/bin/ash -o pipefail -c apk add --no-cache coreutils=9.1-r0 wget=1.21.3-r0' returned a non-zero code: 2
```

![image](https://user-images.githubusercontent.com/13190808/230788345-2b1c8389-cdc6-456c-81b4-53ff0d0727dd.png)

**Comment by aatrubilin** [comment]
@gizeasy, @svarogmaliby, could you please try to install latest addon version?

**Comment by gizeasy** [comment]
fixed
