### ISSUE TITLE
dont work on Home Assistant 2023.8.2 Supervisor 2023.08.1 Operating System 10.4 Frontend 20230802.0 - latest

### ISSUE THREAD

**Issue by Oysed** [aatrubilin/hassio-torrserver#5]
"events_url": "https://api.github.com/users/YouROK/events{/privacy}",
        "received_events_url": "https://api.github.com/users/YouROK/received_events",
        "type": "User",
        "site_admin": false
      },
      "content_type": "application/octet-stream",
      "state": "uploaded",
      "size": 36479488,
      "download_count": 45,
      "created_at": "2023-08-15T08:57:55Z",
      "updated_at": "2023-08-15T08:57:58Z",
      "browser_download_url": "https://github.com/YouROK/TorrServer/releases/download/MatriX.125/TorrServer-windows-386.exe"
    },
    {
      "url": "https://api.github.com/repos/YouROK/TorrServer/releases/assets/121567902",
      "id": 121567902,
      "node_id": "RA_kwDOCLyS5s4HPvqe",
      "name": "TorrServer-windows-amd64.exe",
      "label": null,
      "uploader": {
        "login": "YouROK",
        "id": 4067300,
        "node_id": "MDQ6VXNlcjQwNjczMDA=",
        "avatar_url": "https://avatars.githubusercontent.com/u/4067300?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/YouROK",
        "html_url": "https://github.com/YouROK",
        "followers_url": "https://api.github.com/users/YouROK/followers",
        "following_url": "https://api.github.com/users/YouROK/following{/other_user}",
        "gists_url": "https://api.github.com/users/YouROK/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/YouROK/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/YouROK/subscriptions",
        "organizations_url": "https://api.github.com/users/YouROK/orgs",
        "repos_url": "https://api.github.com/users/YouROK/repos",
        "events_url": "https://api.github.com/users/YouROK/events{/privacy}",
        "received_events_url": "https://api.github.com/users/YouROK/received_events",
        "type": "User",
        "site_admin": false
      },
      "content_type": "application/octet-stream",
      "state": "uploaded",
      "size": 37710848,
      "download_count": 180,
      "created_at": "2023-08-15T08:57:58Z",
      "updated_at": "2023-08-15T08:58:00Z",
      "browser_download_url": "https://github.com/YouROK/TorrServer/releases/download/MatriX.125/TorrServer-windows-amd64.exe"
    }
  ],
  "tarball_url": "https://api.github.com/repos/YouROK/TorrServer/tarball/MatriX.125",
  "zipball_url": "https://api.github.com/repos/YouROK/TorrServer/zipball/MatriX.125",
  "body": "Обновление движка\r\n\r\nСпасибо\r\n@tsynik\r\n@FaintGhost",
  "reactions": {
    "url": "https://api.github.com/repos/YouROK/TorrServer/releases/117277851/reactions",
    "total_count": 6,
    "+1": 4,
    "-1": 0,
    "laugh": 0,
    "hooray": 2,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "mentions_count": 2
}
TS_VERSION=MatriX.125
TS_RUNFILE=/share/torrserver/TorrServer-MatriX.125
Checking existed torrserver
rm -f TorrServer-*
Downloading TorrServer-linux-amd64-MatriX.125...
wget: unrecognized option: v
BusyBox v1.36.1 (2023-06-02 00:42:02 UTC) multi-call binary.
Usage: wget [-cqS] [--spider] [-O FILE] [-o LOGFILE] [--header STR]
	[--post-data STR | --post-file FILE] [-Y on/off]
	[-P DIR] [-U AGENT] [-T SEC] URL...
Retrieve files via HTTP or FTP
	--spider	Only check URL existence: $? is 0 if exists
	--header STR	Add STR (of form 'header: value') to headers
	--post-data STR	Send STR using POST method
	--post-file FILE	Send FILE using POST method
	-c		Continue retrieval of aborted transfer
	-q		Quiet
	-P DIR		Save to DIR (default .)
	-S    		Show server response
	-T SEC		Network read timeout is SEC seconds
	-O FILE		Save to FILE ('-' for stdout)
	-o LOGFILE	Log messages to FILE
	-U STR		Use STR for User-Agent header
	-Y on/off	Use proxy
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by aatrubilin** [comment]
Hey @Oysed 
I just pushed minor update.

Try to install addon v0.2.0.

**Comment by Oysed** [comment]
Thanx! Now its work!
Спасибо!
