### ISSUE TITLE
Кнопка на боковой панели

### ISSUE THREAD

**Issue by MartynIden** [aatrubilin/hassio-torrserver#7]
Можно добавить кнопку на боковой панели?
потому что вручную сделать кнопку на http сервис не получается если сервер использует https а пробрасывать порт на внешку не вариант

**Comment by aatrubilin** [comment]
Привет. 
Для это кнопки, если я не ошибаюсь, нужно подключить ingress для аддона.

Я пытался реализовать это на первых этапах, но сталкивался с проблемами (если честно не помню что за проблемы были).

Но идея классная, как будет время попробую снова реализовать. Вроде с прошлой моей попытки появились новые функции у аддонов, есть шанс что получится. 

Если кто то захочет помочь с этим - буду рад!

**Comment by aatrubilin** [comment]
Привет @MartynIden!

Изучил подробнее вопрос - и кажется без доработки torrserver сделать это будет крайне сложно.

Проблема в абсолютных путях к статике на стороне torrserver, например js код подгружается по ссылке `/js/...`
А т.к. доступ через боковую кнопку предполагает что путь должен быть `https://home/api/hassio_ingress/{addon-id}/js/...` 

![image](https://github.com/aatrubilin/hassio-torrserver/assets/29011393/1fb55522-38c3-46d0-8c5a-9d5b50b192da)

Подобная тема на форуме ha: https://community.home-assistant.io/t/360529

**Comment by aatrubilin** [comment]
@MartynIden привет!

Получилось реализовать работу через ingress - теперь есть возможность добавить кнопку на боковой панели в версии 1.0.0-MatriX.132

Протестируй, пожалуйста.

Если успешно заработает - скинь, пожалуйста вот эту часть лога аддона (чтобы понять на какой архитектуре работает успешно)

Если не сработает - то лучше весь лог)

![image](https://github.com/aatrubilin/hassio-torrserver/assets/29011393/6125f3ee-cca3-4d76-8694-d32725ea07e1)
