### ISSUE TITLE
Не стартует, ошибка в логах

### ISSUE THREAD

**Issue by baradetsky** [aatrubilin/hassio-torrserver#8]
Установил (пришлось удалить отдельно установленный на серваке ХА)
Аддон не стартует, в логах получаю следующее
```
curl: (7) Failed to connect to supervisor port 80 after 8 ms: Couldn't connect to server
[14:10:12] ERROR: Something went wrong contacting the API
```
ХА супервазед, установлен на дебиан 12

**Comment by aatrubilin** [comment]
Fixed in v0.2.7 (https://github.com/aatrubilin/hassio-torrserver/commit/bb7ccbacf6127cc02a4b48e37cff3011d299bbf0)
