### ISSUE TITLE
Не устанавливается. returned a non-zero code: 1

### ISSUE THREAD

**Issue by GampiST** [aatrubilin/hassio-torrserver#9]
При попытке установить аддон выдает следующую ошибку. HAOS обновлен до последней версии.
HAOS amd 64

Не удалось установить дополнение.
The command '/bin/ash -o pipefail -c apk add --no-cache coreutils=9.3-r1 wget=1.21.4-r0' returned a non-zero code: 1

<img width="722" alt="Error" src="https://github.com/aatrubilin/hassio-torrserver/assets/63113799/364ada38-f892-4847-9eb9-eb3bb1ff9f67">

**Comment by aatrubilin** [comment]
Привет @GampiST!

Обновил зависимости до актуальных - попробуй версию 0.2.9, должно быть все ок

**Comment by GampiST** [comment]
Установился, но теперь Permission denied
/run.sh: line 45: /share/torrserver/TorrServer-MatriX.128: Permission denied
<img width="1222" alt=" 2024-01-10 о 13 56 20" src="https://github.com/aatrubilin/hassio-torrserver/assets/63113799/fbd2ee56-b511-4817-92eb-0993dd95391e">

**Comment by aatrubilin** [comment]
Что то новенькое, и весьма странное, если система установлена как HA OS.
Папка `/share` мапится с хоста в аддон:

https://github.com/aatrubilin/hassio-torrserver/blob/master/torrserver/config.yaml#L20
https://developers.home-assistant.io/docs/add-ons/configuration#optional-configuration-options

Такое ощущение что где-то проблема с самим HA. 

Заведи плс отдельный issue с этой проблемой, версии core/supervisor/os
Я по возомжности поищу решение
![image](https://github.com/aatrubilin/hassio-torrserver/assets/29011393/0b69605b-4544-4820-9a39-ee2e58aa4cd2)
